name: Docker deploy on AWS ECR

on:
  push:
    branches:
      - main

jobs:
  build-and-push-on-aws-ecr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to ECR
        run: aws ecr get-login-password --region eu-west-3 | docker login --username AWS --password-stdin 587222088192.dkr.ecr.eu-west-3.amazonaws.com
      - name: Create the Docker image
        run: docker build -t chasseautresor .
      - name: Tag the image
        run: docker tag chasseautresor:latest 587222088192.dkr.ecr.eu-west-3.amazonaws.com/chasseautresor:latest
      - name: Push the image to ECR
        run: docker push 587222088192.dkr.ecr.eu-west-3.amazonaws.com/chasseautresor:latest
